C***********************************************************************
C  Persistent non-interactive XFOIL kernel session.
C
C  This executable keeps one XFOIL COMMON-block state alive across multiple
C  SOLVE commands. The outer Python JSON-lines worker can use it as a stable
C  process boundary while preserving warm-started panel and boundary-layer
C  state between compatible requests.
C***********************************************************************
      PROGRAM XFOIL_KERNEL_SESSION
      INCLUDE 'XFOIL.INC'
C
      INTEGER MAXALF
      PARAMETER (MAXALF = 256)
C
      CHARACTER*16 AIRFOIL_TYPE
      CHARACTER*16 CACHED_AIRFOIL_TYPE
      CHARACTER*256 COORDINATE_FILE
      CHARACTER*256 CACHED_COORDINATE_FILE
      CHARACTER*256 COMMAND
      CHARACTER*128 ERROR_MESSAGE
      INTEGER NACA_CODE
      INTEGER CACHED_NACA_CODE
      INTEGER N_ALPHA
      INTEGER PANEL_COUNT
      INTEGER CACHED_PANEL_COUNT
      INTEGER I
      REAL ALPHA_DEG(MAXALF)
      REAL REYNOLDS_NUMBER
      REAL CACHED_REYNOLDS_NUMBER
      REAL MACH_NUMBER
      REAL CACHED_MACH_NUMBER
      REAL NCRIT_TOP
      REAL CACHED_NCRIT_TOP
      REAL NCRIT_BOTTOM
      REAL CACHED_NCRIT_BOTTOM
      REAL XTR_TOP
      REAL CACHED_XTR_TOP
      REAL XTR_BOTTOM
      REAL CACHED_XTR_BOTTOM
      LOGICAL VISCOUS
      LOGICAL CACHED_VISCOUS
      LOGICAL PANEL_AIRFOIL
      LOGICAL CACHED_PANEL_AIRFOIL
      LOGICAL STATE_READY
      LOGICAL GEOMETRY_CHANGED
      LOGICAL OPTIONS_CHANGED
      LOGICAL CASE_OK
C
      NAMELIST /XKCASE/ AIRFOIL_TYPE, COORDINATE_FILE, NACA_CODE,
     &  VISCOUS, REYNOLDS_NUMBER, MACH_NUMBER, NCRIT_TOP,
     &  NCRIT_BOTTOM, XTR_TOP, XTR_BOTTOM, ITMAX, PANEL_COUNT,
     &  PANEL_AIRFOIL, N_ALPHA, ALPHA_DEG
C
      VERSION = 6.99
      CALL INIT
      CALL XK_DISABLE_PLOTTING
C
      STATE_READY = .FALSE.
      CACHED_AIRFOIL_TYPE = ' '
      CACHED_COORDINATE_FILE = ' '
      CACHED_NACA_CODE = -999
      CACHED_PANEL_COUNT = -999
      CACHED_PANEL_AIRFOIL = .FALSE.
      CACHED_VISCOUS = .FALSE.
      CACHED_REYNOLDS_NUMBER = -1.0
      CACHED_MACH_NUMBER = -1.0
      CACHED_NCRIT_TOP = -1.0
      CACHED_NCRIT_BOTTOM = -1.0
      CACHED_XTR_TOP = -1.0
      CACHED_XTR_BOTTOM = -1.0
C
      WRITE(*,7000)
      CALL FLUSH(6)
C
  100 CONTINUE
      COMMAND = ' '
      READ(5,9000,END=990,ERR=910) COMMAND
      IF(COMMAND .EQ. ' ') GO TO 100
C
      IF(COMMAND(1:4) .EQ. 'PING') THEN
        WRITE(*,7010)
        CALL FLUSH(6)
        GO TO 100
      ELSEIF(COMMAND(1:26) .EQ. 'RESET_BOUNDARY_LAYER_STATE')
     &  THEN
        CALL XK_RESET_BOUNDARY_LAYER_STATE
        WRITE(*,7040)
        CALL FLUSH(6)
        GO TO 100
      ELSEIF(COMMAND(1:8) .EQ. 'SHUTDOWN') THEN
        WRITE(*,7020)
        CALL FLUSH(6)
        STOP
      ELSEIF(COMMAND(1:5) .EQ. 'SOLVE') THEN
        GO TO 200
      ELSE
        WRITE(*,7030) COMMAND
        CALL FLUSH(6)
        GO TO 100
      ENDIF
C
  200 CONTINUE
      CALL XK_DEFAULT_CASE(MAXALF,AIRFOIL_TYPE,COORDINATE_FILE,
     &  NACA_CODE,VISCOUS,REYNOLDS_NUMBER,MACH_NUMBER,NCRIT_TOP,
     &  NCRIT_BOTTOM,XTR_TOP,XTR_BOTTOM,ITMAX,PANEL_COUNT,
     &  PANEL_AIRFOIL,N_ALPHA,ALPHA_DEG)
C
      READ(5,NML=XKCASE,ERR=920,END=990)
C
      CALL XK_VALIDATE_CASE(MAXALF,N_ALPHA,ITMAX,PANEL_COUNT,CASE_OK,
     &  ERROR_MESSAGE)
      IF(.NOT.CASE_OK) THEN
        WRITE(*,7100) ERROR_MESSAGE
        CALL FLUSH(6)
        GO TO 100
      ENDIF
C
      GEOMETRY_CHANGED = .NOT.STATE_READY
      IF(.NOT.GEOMETRY_CHANGED) THEN
        IF(AIRFOIL_TYPE .NE. CACHED_AIRFOIL_TYPE)
     &    GEOMETRY_CHANGED = .TRUE.
        IF(COORDINATE_FILE .NE. CACHED_COORDINATE_FILE)
     &    GEOMETRY_CHANGED = .TRUE.
        IF(NACA_CODE .NE. CACHED_NACA_CODE) GEOMETRY_CHANGED = .TRUE.
        IF(PANEL_COUNT .NE. CACHED_PANEL_COUNT)
     &    GEOMETRY_CHANGED = .TRUE.
        IF(PANEL_AIRFOIL .NEQV. CACHED_PANEL_AIRFOIL)
     &    GEOMETRY_CHANGED = .TRUE.
      ENDIF
C
      IF(GEOMETRY_CHANGED) THEN
        CALL XK_LOAD_GEOMETRY(AIRFOIL_TYPE,COORDINATE_FILE,
     &    NACA_CODE,PANEL_COUNT,PANEL_AIRFOIL,CASE_OK,ERROR_MESSAGE)
        IF(.NOT.CASE_OK) THEN
          WRITE(*,7100) ERROR_MESSAGE
          CALL FLUSH(6)
          GO TO 100
        ENDIF
C
        CACHED_AIRFOIL_TYPE = AIRFOIL_TYPE
        CACHED_COORDINATE_FILE = COORDINATE_FILE
        CACHED_NACA_CODE = NACA_CODE
        CACHED_PANEL_COUNT = PANEL_COUNT
        CACHED_PANEL_AIRFOIL = PANEL_AIRFOIL
        STATE_READY = .TRUE.
      ENDIF
C
      OPTIONS_CHANGED = GEOMETRY_CHANGED
      IF(.NOT.OPTIONS_CHANGED) THEN
        IF(VISCOUS .NEQV. CACHED_VISCOUS) OPTIONS_CHANGED = .TRUE.
        IF(ABS(REYNOLDS_NUMBER-CACHED_REYNOLDS_NUMBER) .GT. 1.0E-9)
     &    OPTIONS_CHANGED = .TRUE.
        IF(ABS(MACH_NUMBER-CACHED_MACH_NUMBER) .GT. 1.0E-12)
     &    OPTIONS_CHANGED = .TRUE.
        IF(ABS(NCRIT_TOP-CACHED_NCRIT_TOP) .GT. 1.0E-12)
     &    OPTIONS_CHANGED = .TRUE.
        IF(ABS(NCRIT_BOTTOM-CACHED_NCRIT_BOTTOM) .GT. 1.0E-12)
     &    OPTIONS_CHANGED = .TRUE.
        IF(ABS(XTR_TOP-CACHED_XTR_TOP) .GT. 1.0E-12)
     &    OPTIONS_CHANGED = .TRUE.
        IF(ABS(XTR_BOTTOM-CACHED_XTR_BOTTOM) .GT. 1.0E-12)
     &    OPTIONS_CHANGED = .TRUE.
      ENDIF
C
      CALL XK_APPLY_OPTIONS(VISCOUS,REYNOLDS_NUMBER,MACH_NUMBER,
     &  NCRIT_TOP,NCRIT_BOTTOM,XTR_TOP,XTR_BOTTOM,OPTIONS_CHANGED)
      CALL XK_PREPARE_OPERATING_POINT
C
      WRITE(*,8000) VERSION, N, VISCOUS, REINF1, MINF1,
     &  ACRIT(1), ACRIT(2), XSTRIP(1), XSTRIP(2),
     &  GEOMETRY_CHANGED, OPTIONS_CHANGED
C
      DO I = 1, N_ALPHA
        CALL XK_SOLVE_ALPHA_POINT(ALPHA_DEG(I),ITMAX)
        WRITE(*,8100) I, ADEG, CL, CD, CM, CDP, LVCONV, RMSBL,
     &    XOCTR(1), XOCTR(2), TFORCE(1), TFORCE(2)
      ENDDO
C
      CACHED_VISCOUS = VISCOUS
      CACHED_REYNOLDS_NUMBER = REYNOLDS_NUMBER
      CACHED_MACH_NUMBER = MACH_NUMBER
      CACHED_NCRIT_TOP = NCRIT_TOP
      CACHED_NCRIT_BOTTOM = NCRIT_BOTTOM
      CACHED_XTR_TOP = XTR_TOP
      CACHED_XTR_BOTTOM = XTR_BOTTOM
C
      WRITE(*,7110)
      CALL FLUSH(6)
      GO TO 100
C
  910 CONTINUE
      WRITE(*,7100) 'could not read worker command'
      CALL FLUSH(6)
      GO TO 100
C
  920 CONTINUE
      WRITE(*,7100) 'could not read XKCASE namelist'
      CALL FLUSH(6)
      GO TO 100
C
  990 CONTINUE
      STOP
C
 7000 FORMAT('XK_READY schema=1')
 7010 FORMAT('XK_OK ping')
 7020 FORMAT('XK_BYE')
 7030 FORMAT('XK_ERROR unknown command: ',A)
 7040 FORMAT('XK_OK reset_boundary_layer_state')
 7100 FORMAT('XK_ERROR ',A)
 7110 FORMAT('XK_END')
 8000 FORMAT('XK_HEADER schema=1 version=',F6.2,' n_panels=',I5,
     & ' viscous=',L1,' reynolds=',ES16.8,' mach=',ES16.8,
     & ' ncrit_top=',ES16.8,' ncrit_bottom=',ES16.8,
     & ' xtr_top=',ES16.8,' xtr_bottom=',ES16.8,
     & ' geometry_changed=',L1,' options_changed=',L1)
 8100 FORMAT('XK_POINT ',I5,1X,F14.6,1X,ES24.16,1X,ES24.16,
     & 1X,ES24.16,1X,ES24.16,1X,L1,1X,ES16.8,1X,ES16.8,
     & 1X,ES16.8,1X,L1,1X,L1)
 9000 FORMAT(A)
      END
