C***********************************************************************
C  Minimal non-interactive XFOIL kernel driver.
C
C  This file is local XFOIL kernel driver code. It links against the tracked
C  extracted kernel sources and shared non-interactive kernel core routines.
C***********************************************************************
      PROGRAM XFOIL_KERNEL_DRIVER
      INCLUDE 'XFOIL.INC'
C
      INTEGER MAXALF
      PARAMETER (MAXALF = 256)
C
      CHARACTER*16 AIRFOIL_TYPE
      CHARACTER*256 COORDINATE_FILE
      INTEGER NACA_CODE
      INTEGER N_ALPHA
      INTEGER PANEL_COUNT
      INTEGER I
      REAL ALPHA_DEG(MAXALF)
      REAL REYNOLDS_NUMBER
      REAL MACH_NUMBER
      REAL NCRIT_TOP
      REAL NCRIT_BOTTOM
      REAL XTR_TOP
      REAL XTR_BOTTOM
      LOGICAL VISCOUS
      LOGICAL PANEL_AIRFOIL
      LOGICAL CASE_OK
      CHARACTER*128 ERROR_MESSAGE
C
      NAMELIST /XKCASE/ AIRFOIL_TYPE, COORDINATE_FILE, NACA_CODE,
     &  VISCOUS, REYNOLDS_NUMBER, MACH_NUMBER, NCRIT_TOP,
     &  NCRIT_BOTTOM, XTR_TOP, XTR_BOTTOM, ITMAX, PANEL_COUNT,
     &  PANEL_AIRFOIL, N_ALPHA, ALPHA_DEG
C
      VERSION = 6.99
      CALL INIT
      CALL XK_DISABLE_PLOTTING
      CALL XK_DEFAULT_CASE(MAXALF,AIRFOIL_TYPE,COORDINATE_FILE,
     &  NACA_CODE,VISCOUS,REYNOLDS_NUMBER,MACH_NUMBER,NCRIT_TOP,
     &  NCRIT_BOTTOM,XTR_TOP,XTR_BOTTOM,ITMAX,PANEL_COUNT,
     &  PANEL_AIRFOIL,N_ALPHA,ALPHA_DEG)
C
      READ(5,NML=XKCASE,ERR=900,END=900)
      CALL XK_VALIDATE_CASE(MAXALF,N_ALPHA,ITMAX,PANEL_COUNT,CASE_OK,
     &  ERROR_MESSAGE)
      IF(.NOT.CASE_OK) THEN
        WRITE(*,*) 'XK_ERROR ', ERROR_MESSAGE
        STOP 2
      ENDIF
C
      CALL XK_LOAD_GEOMETRY(AIRFOIL_TYPE,COORDINATE_FILE,NACA_CODE,
     &  PANEL_COUNT,PANEL_AIRFOIL,CASE_OK,ERROR_MESSAGE)
      IF(.NOT.CASE_OK) THEN
        WRITE(*,*) 'XK_ERROR ', ERROR_MESSAGE
        STOP 3
      ENDIF
C
      CALL XK_APPLY_OPTIONS(VISCOUS,REYNOLDS_NUMBER,MACH_NUMBER,
     &  NCRIT_TOP,NCRIT_BOTTOM,XTR_TOP,XTR_BOTTOM,.TRUE.)
      CALL XK_PREPARE_OPERATING_POINT
C
      WRITE(*,8000) VERSION, N, VISCOUS, REINF1, MINF1,
     &  ACRIT(1), ACRIT(2), XSTRIP(1), XSTRIP(2)
C
      DO I = 1, N_ALPHA
        CALL XK_SOLVE_ALPHA_POINT(ALPHA_DEG(I),ITMAX)
        WRITE(*,8100) I, ADEG, CL, CD, CM, CDP, LVCONV, RMSBL,
     &    XOCTR(1), XOCTR(2), TFORCE(1), TFORCE(2)
      ENDDO
C
      WRITE(*,*) 'XK_END'
      STOP
C
  900 CONTINUE
      WRITE(*,*) 'XK_ERROR could not read XKCASE namelist'
      STOP 1
C
 8000 FORMAT('XK_HEADER schema=1 version=',F6.2,' n_panels=',I5,
     & ' viscous=',L1,' reynolds=',ES16.8,' mach=',ES16.8,
     & ' ncrit_top=',ES16.8,' ncrit_bottom=',ES16.8,
     & ' xtr_top=',ES16.8,' xtr_bottom=',ES16.8)
 8100 FORMAT('XK_POINT ',I5,1X,F14.6,1X,ES24.16,1X,ES24.16,
     & 1X,ES24.16,1X,ES24.16,1X,L1,1X,ES16.8,1X,ES16.8,
     & 1X,ES16.8,1X,L1,1X,L1)
      END
